#version: '3.1'
#
#services:
#  db:
#    image: postgres
#    restart: always
#    environment:
#      POSTGRES_DB: messaging_app
#      POSTGRES_USER: user
#      POSTGRES_PASSWORD: secretpassword
#    ports:
#      - "5432:5432"
##    volumes:
##      - ./db-init:/docker-entrypoint-initdb.d
