spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/messaging_app
    username: user
    password: secretpassword
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true