--CREATE TABLE IF NOT EXISTS users (
--    id SERIAL PRIMARY KEY,
--    nickname VARCHAR(255) UNIQUE NOT NULL
--);
--
--CREATE TABLE IF NOT EXISTS messages (
--    id SERIAL PRIMARY KEY,
--    sender_id BIGINT NOT NULL REFERENCES users(id),
--    receiver_id BIGINT NOT NULL REFERENCES users(id),
--    content TEXT NOT NULL,
--    timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP
--);
